# Get the data

**Problem Statement**

Given a NumPy matrix of shape (n, n), remove all the odd elements from the matrix and return a new matrix of shape (k, k) consisting of all the remaining even elements from the original matrix.

**Input Format**
```
A 2d list is taken as input which is first typecasted to a NumPy array and then passed to the function as argument.
```

**Output Format**
```
2d NumPy array is printed
```
**Sample Input and Output**

> Sample Input:
```
[[ 7, 4, 8, 5, 1],
 [ 8, 0, 11, 3, 5],
 [ 9, 6, 3, 5, 0],
 [ 1, 5, 7, 3, 2],
 [ 4, 7, 2, 9, 1]]
```
> Sample Output:
```
[[4 8 8]
 [0 6 0]
 [2 4 2]]
```

**Sample Explanation:**

In the 5x5 matrix when we removed all the odd numbers we were left with 9 numbers, and hence 9 numbers can be converted to (3x3).

**Note**: Assume that the number of even elements in the given matrix will always be a perfect square. Also observe that the relative order of elements in the new matrix is preserved as it was in the original matrix ie. the first 4 is before 8 in the matrix as it was in the original matrix.

In [1]:
import numpy as np

def new_mat(mat):
    '''
    mat --> A 2D numpy array
    Output --> A 2D numpy array is expected to be returned
    '''
    
    ## Step 1: Filter out  even elements from array (Masking)
    new_matrix = mat[ mat%2 == 0]
    
    ## Step 2: Get the length of new matrix (Recall that Masking will return 1D array)
    new_len = len(new_matrix)
    
    ## Step 3: Find the shape using new_len
    new_shape = int(np.sqrt(new_len))
    
    ## Step 4: Reshape the new matrix
    new_matrix = new_matrix.reshape(new_shape, new_shape)
    
    return new_matrix


mat = np.array([[7,4,8,5,1],[8,0,11,3,5],[9,6,3,5,0],[1,5,7,3,2],[4,7,2,9,1]])  #np.array(eval(input()))

print(new_mat(mat))

[[4 8 8]
 [0 6 0]
 [2 4 2]]
