# Square Matrix

**Problem Statement**

Given an array starting from 0 to x (0 and x both included). Perform the following operations on the array.
1. Separate even and odd numbers from the array.
2. Now, reshape each of the two arrays to square matrix. If it is not possible return - 1.
3. Stack both the square matrices vertically, with the even on top of the odd one.
4. Finally, return the mean of the each column.

**Input Format**
```
x
```
**Output Format**
```
array
```

**Sample Input and Output**
> Sample Input -
```
49
```
> Sample Output 
```    
[20.5 22.5 24.5 26.5 28.5]
```

> Sample Explanation -
- Extract the even numbers array:
```
array([ 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48])
```
- Extract the odd numbers array:
```
array([ 1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49])
```
- Reshape each of the array to square matrices
```
array([ 0, 2, 4, 6, 8],
      [10, 12, 14, 16, 18],
      [20, 22, 24, 26, 28],
      [30, 32, 34, 36, 38],
      [40, 42, 44, 46, 48]])
and
array([ 1, 3, 5, 7, 9],
      [11, 13, 15, 17, 19],
      [21, 23, 25, 27, 29],
      [31, 33, 35, 37, 39],
      [41, 43, 45, 47, 49]])
```
- Stack both the arrays vertically with even on top of odd
```
array([[ 0, 2, 4, 6, 8],
      [10, 12, 14, 16, 18],
      [20, 22, 24, 26, 28],
      [30, 32, 34, 36, 38],
      [40, 42, 44, 46, 48],
      [ 1, 3, 5, 7, 9],
      [11, 13, 15, 17, 19],
      [21, 23, 25, 27, 29],
      [31, 33, 35, 37, 39],
      [41, 43, 45, 47, 49]])
```      
- Return the mean of each column of the stacked arrays
```
[20.5 22.5 24.5 26.5 28.5]
```
Mean of column 1 is (0+10+20+30+40+1+11+21+31+41)/10 = 20.5 

In [1]:
import numpy as np

def function(x):
    '''
    x --> int
    '''
    
    array = np.arange(0, x+1)
    
    a_even = array[ array%2 == 0]
    a_odd = array[ array%2 == 1]
    
    n1 = len(a_even)
    n2 = len(a_odd)
    
    len_even = int(np.sqrt(n1))
    len_odd = int(np.sqrt(n2))
    
    if (len_even * len_even != n1) or (len_odd * len_odd != n2):
        return -1
    
    mat1 = a_even.reshape(len_even, len_even)
    mat2 = a_odd.reshape(len_odd, len_odd)
    
    stacked_mat = np.vstack((mat1, mat2))
    
    ans = np.mean(stacked_mat, axis = 0)
    
    
    return ans

x = 49 ##int(input())

print(function(x))

[20.5 22.5 24.5 26.5 28.5]
