# Rotate the Array

**Problem Statement**

Given an array in form of a matrix of size (n, n), rotate the matrix clockwise by 90°

**Input Format**
```
A 2d numpy array
```
**Output Format**
```
A 2d numpy array
```

**Sample Input and Output**

> Sample Input:
```
[[1 2 3]
 [4 5 6]
 [7 8 9]]
```
> Sample Output:
```
[[7 4 1]
 [8 5 2]
 [9 6 3]]
```
Note: Try Transpose / reversing.

In [1]:
import numpy as np
def rotate_img(mat):
    '''
    mat --> A 2D numpy array
    output --> A 2D numpy array is expected to be returned 
    '''
    # Transposing the matrix
    mat1 = mat.T
    # slicing the matrix to reverse
    ans = mat1[:,::-1]
    
    return ans

mat = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])   #np.array(eval(input()))
print(rotate_img(mat))

[[7 4 1]
 [8 5 2]
 [9 6 3]]
